Do return to originl working direcotry if awesome-shell ref is present

diff --git a/awesome-bash b/awesome-bash
--- a/awesome-bash
+++ b/awesome-bash
@@ -115,6 +115,7 @@ if [ -n "$awesome_shell_commit_ref" ];then
     commons_content=$(git show "$awesome_shell_commit_ref:commons") || fatal "Cannot find commons in '$awesome_shell_commit_ref'"
     export awesome_shell_commons_file_dir="$dir"
     eval "$commons_content"
+    cd - 1>/dev/null 2>&1 || fatal "Cannot return to original working directory"
 elif [ -x "$dir/commons" ]; then
     # shellcheck disable=SC1090
     source "$dir/commons"
